import type { NavGroup } from '~/types/docs';

export const docsNav: NavGroup[] = [
  {
    title: 'Getting Started',
    items: [{ title: 'Introduction', path: '/docs' }],
  },
  {
    title: 'Text Animations',
    items: [
      { title: 'ASCII Text', path: '/docs/text-animations/ascii-text' },
      { title: 'Blur Text', path: '/docs/text-animations/blur-text' },
      { title: 'Circular Text', path: '/docs/text-animations/circular-text' },
      { title: 'Count Up', path: '/docs/text-animations/count-up' },
      { title: 'Curved Loop', path: '/docs/text-animations/curved-loop' },
      { title: 'Decrypted Text', path: '/docs/text-animations/decrypted-text' },
      { title: 'Falling Text', path: '/docs/text-animations/falling-text' },
      { title: 'Fuzzy Text', path: '/docs/text-animations/fuzzy-text' },
      { title: 'Glitch Text', path: '/docs/text-animations/glitch-text' },
      { title: 'Gradient Text', path: '/docs/text-animations/gradient-text' },
      { title: 'Hyper Text', path: '/docs/text-animations/hyper-text' },
      { title: 'Logo Loop', path: '/docs/text-animations/logo-loop' },
      { title: 'Rotating Text', path: '/docs/text-animations/rotating-text' },
      { title: 'Scrambled Text', path: '/docs/text-animations/scrambled-text' },
      { title: 'Scroll Based Velocity', path: '/docs/text-animations/scroll-based-velocity' },
      { title: 'Scroll Float', path: '/docs/text-animations/scroll-float' },
      { title: 'Scroll Reveal', path: '/docs/text-animations/scroll-reveal' },
      { title: 'Shiny Text', path: '/docs/text-animations/shiny-text' },
      { title: 'Shuffle', path: '/docs/text-animations/shuffle' },
      { title: 'Split Text', path: '/docs/text-animations/split-text' },
      { title: 'Text Animate', path: '/docs/text-animations/text-animate' },
      { title: 'Text Cursor', path: '/docs/text-animations/text-cursor' },
      { title: 'Text Pressure', path: '/docs/text-animations/text-pressure' },
      { title: 'Text Type', path: '/docs/text-animations/text-type' },
      { title: 'True Focus', path: '/docs/text-animations/true-focus' },
      { title: 'Variable Proximity', path: '/docs/text-animations/variable-proximity' },
    ],
  },
  {
    title: 'Components',
    items: [
      { title: 'Animated List', path: '/docs/components/animated-list' },
      { title: 'Auth Modal', path: '/docs/components/auth-modal' },
      { title: 'Bounce Cards', path: '/docs/components/bounce-cards' },
      { title: 'Bubble Menu', path: '/docs/components/bubble-menu' },
      { title: 'Card Nav', path: '/docs/components/card-nav' },
      { title: 'Card Swap', path: '/docs/components/card-swap' },
      { title: 'Carousel', path: '/docs/components/carousel' },
      { title: 'Chroma Grid', path: '/docs/components/chroma-grid' },
      { title: 'Circular Gallery', path: '/docs/components/circular-gallery' },
      { title: 'Collection Surfer', path: '/docs/components/collection-surfer' },
      { title: 'Command Menu', path: '/docs/components/command-menu' },
      { title: 'Counter', path: '/docs/components/counter' },
      { title: 'Decay Card', path: '/docs/components/decay-card' },
      { title: 'Dome Gallery', path: '/docs/components/dome-gallery' },
      { title: 'Elastic Slider', path: '/docs/components/elastic-slider' },
      { title: 'Flight Status Card', path: '/docs/components/flight-status-card' },
      { title: 'Flowing Menu', path: '/docs/components/flowing-menu' },
      { title: 'Flying Posters', path: '/docs/components/flying-posters' },
      { title: 'Fluid Glass', path: '/docs/components/fluid-glass' },
      { title: 'Folder', path: '/docs/components/folder' },
      { title: 'GitHub Calendar', path: '/docs/components/github-calendar' },
      { title: 'Glass Icons', path: '/docs/components/glass-icons' },
      { title: 'Glass Surface', path: '/docs/components/glass-surface' },
      { title: 'Gooey Nav', path: '/docs/components/gooey-nav' },
      { title: 'Infinite Menu', path: '/docs/components/infinite-menu' },
      { title: 'Lanyard', path: '/docs/components/lanyard' },
      { title: 'Layered Stack', path: '/docs/components/layered-stack' },
      { title: 'Magic Bento', path: '/docs/components/magic-bento' },
      { title: 'Magnetic Dock', path: '/docs/components/magnetic-dock' },
      { title: 'Masonry', path: '/docs/components/masonry' },
      { title: 'Model Viewer', path: '/docs/components/model-viewer' },
      { title: 'Node Diagram', path: '/docs/components/node-diagram' },
      { title: 'Orbit Images', path: '/docs/components/orbit-images' },
      { title: 'Pill Nav', path: '/docs/components/pill-nav' },
      { title: 'Pixel Card', path: '/docs/components/pixel-card' },
      { title: 'Profile Card', path: '/docs/components/profile-card' },
      { title: 'Reflective Card', path: '/docs/components/reflective-card' },
      { title: 'Scroll Choreography', path: '/docs/components/scroll-choreography' },
      { title: 'Scroll Stack', path: '/docs/components/scroll-stack' },
      { title: 'Scrub Input', path: '/docs/components/scrub-input' },
      { title: 'Showcase Card', path: '/docs/components/showcase-card' },
      { title: 'Spotlight Card', path: '/docs/components/spotlight-card' },
      { title: 'Stack', path: '/docs/components/stack' },
      { title: 'Staggered Menu', path: '/docs/components/staggered-menu' },
      { title: 'Stepper', path: '/docs/components/stepper' },
      { title: 'Sticker Peel', path: '/docs/components/sticker-peel' },
      { title: 'Testimonial Marquee', path: '/docs/components/testimonial-marquee' },
      { title: 'Tilted Card', path: '/docs/components/tilted-card' },
    ],
  },
  {
    title: 'Visual Effects',
    items: [
      { title: 'Border Beam', path: '/docs/visual-effects/border-beam' },
      { title: 'Closing Plasma', path: '/docs/visual-effects/closing-plasma' },
      { title: 'Dither Gradient', path: '/docs/visual-effects/dither-gradient' },
      { title: 'Liquid Blob', path: '/docs/visual-effects/liquid-blob' },
      { title: 'Magnet Lines', path: '/docs/visual-effects/magnet-lines' },
      { title: 'Matrix Rain', path: '/docs/visual-effects/matrix-rain' },
      { title: 'Noise Texture', path: '/docs/visual-effects/noise-texture' },
      { title: 'Particle Galaxy', path: '/docs/visual-effects/particle-galaxy' },
      { title: 'Pixel Canvas', path: '/docs/visual-effects/pixel-canvas' },
    ],
  },
  {
    title: 'Buttons',
    items: [
      { title: 'Interactive Hover Button', path: '/docs/buttons/interactive-hover-button' },
      { title: 'Pulsating Button', path: '/docs/buttons/pulsating-button' },
      { title: 'Shimmer Button', path: '/docs/buttons/shimmer-button' },
    ],
  },
  {
    title: 'Animations',
    items: [
      { title: 'Animated Content', path: '/docs/animations/animated-content' },
      { title: 'Blob Cursor', path: '/docs/animations/blob-cursor' },
      { title: 'Click Spark', path: '/docs/animations/click-spark' },
      { title: 'Crosshair', path: '/docs/animations/crosshair' },
      { title: 'Cubes', path: '/docs/animations/cubes' },
      { title: 'Electric Border', path: '/docs/animations/electric-border' },
      { title: 'Fade Content', path: '/docs/animations/fade-content' },
      { title: 'Ghost Cursor', path: '/docs/animations/ghost-cursor' },
      { title: 'Glare Hover', path: '/docs/animations/glare-hover' },
      { title: 'Gradual Blur', path: '/docs/animations/gradual-blur' },
      { title: 'Image Trail', path: '/docs/animations/image-trail' },
      { title: 'Magic Rings', path: '/docs/animations/magic-rings' },
      { title: 'Magnet', path: '/docs/animations/magnet' },
      { title: 'Meta Balls', path: '/docs/animations/meta-balls' },
      { title: 'Pixel Trail', path: '/docs/animations/pixel-trail' },
      { title: 'Pixel Transition', path: '/docs/animations/pixel-transition' },
      { title: 'Ribbons', path: '/docs/animations/ribbons' },
      { title: 'Shape Blur', path: '/docs/animations/shape-blur' },
      { title: 'Splash Cursor', path: '/docs/animations/splash-cursor' },
      { title: 'Star Border', path: '/docs/animations/star-border' },
      { title: 'Target Cursor', path: '/docs/animations/target-cursor' },
    ],
  },
  {
    title: 'Backgrounds',
    items: [
      { title: 'Antigravity', path: '/docs/backgrounds/antigravity' },
      { title: 'Aurora', path: '/docs/backgrounds/aurora' },
      { title: 'Balatro', path: '/docs/backgrounds/balatro' },
      { title: 'Ballpit', path: '/docs/backgrounds/ballpit' },
      { title: 'Beams', path: '/docs/backgrounds/beams' },
      { title: 'Color Bends', path: '/docs/backgrounds/color-bends' },
      { title: 'Dark Veil', path: '/docs/backgrounds/dark-veil' },
      { title: 'Dot Grid', path: '/docs/backgrounds/dot-grid' },
      { title: 'Evil Eye', path: '/docs/backgrounds/evil-eye' },
      { title: 'Faulty Terminal', path: '/docs/backgrounds/faulty-terminal' },
      { title: 'Floating Lines', path: '/docs/backgrounds/floating-lines' },
      { title: 'Galaxy', path: '/docs/backgrounds/galaxy' },
      { title: 'Gradient Blinds', path: '/docs/backgrounds/gradient-blinds' },
      { title: 'Grainient', path: '/docs/backgrounds/grainient' },
      { title: 'Grid Distortion', path: '/docs/backgrounds/grid-distortion' },
      { title: 'Grid Motion', path: '/docs/backgrounds/grid-motion' },
      { title: 'Grid Scan', path: '/docs/backgrounds/grid-scan' },
      { title: 'Hyperspeed', path: '/docs/backgrounds/hyperspeed' },
      { title: 'Iridescence', path: '/docs/backgrounds/iridescence' },
      { title: 'Laser Flow', path: '/docs/backgrounds/laser-flow' },
      { title: 'Letter Glitch', path: '/docs/backgrounds/letter-glitch' },
      { title: 'Light Pillar', path: '/docs/backgrounds/light-pillar' },
      { title: 'Light Rays', path: '/docs/backgrounds/light-rays' },
      { title: 'Lightning', path: '/docs/backgrounds/lightning' },
      { title: 'Liquid Chrome', path: '/docs/backgrounds/liquid-chrome' },
      { title: 'Liquid Ether', path: '/docs/backgrounds/liquid-ether' },
      { title: 'Metallic Paint', path: '/docs/backgrounds/metallic-paint' },
      { title: 'Orb', path: '/docs/backgrounds/orb' },
      { title: 'Particles', path: '/docs/backgrounds/particles' },
      { title: 'Pixel Blast', path: '/docs/backgrounds/pixel-blast' },
      { title: 'Pixel Snow', path: '/docs/backgrounds/pixel-snow' },
      { title: 'Prism', path: '/docs/backgrounds/prism' },
      { title: 'Prismatic Burst', path: '/docs/backgrounds/prismatic-burst' },
      { title: 'Radar', path: '/docs/backgrounds/radar' },
      { title: 'Ripple Grid', path: '/docs/backgrounds/ripple-grid' },
      { title: 'Shape Grid', path: '/docs/backgrounds/shape-grid' },
      { title: 'Silk', path: '/docs/backgrounds/silk' },
      { title: 'Squares', path: '/docs/backgrounds/squares' },
      { title: 'Threads', path: '/docs/backgrounds/threads' },
      { title: 'Waves', path: '/docs/backgrounds/waves' },
    ],
  },
  {
    title: 'Hero Backgrounds',
    items: [
      { title: 'Animated Gradient', path: '/docs/hero-backgrounds/animated-gradient' },
      { title: 'Dither Prism Hero', path: '/docs/hero-backgrounds/dither-prism-hero' },
      { title: 'Hero Geometric', path: '/docs/hero-backgrounds/hero-geometric' },
      { title: 'WebGL Liquid', path: '/docs/hero-backgrounds/webgl-liquid' },
    ],
  },
];
